baseURL = 'https://blog.mssn.dev/'
languageCode = 'en-us'
title = 'Garbage Collection'
theme = "archie"
copyright = "© musaprg"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "JP blog is [here](https://musaprg.hatenablog.com)"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/musaprg"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/musaprg/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/musaprg/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About me"
url = "https://www.mssn.dev"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

